apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-configmap
data:
  config.cnf: |
    [mariadbd]
    bind-address            = 0.0.0.0
    log_bin = /var/lib/mysql/mariadb-bin
    log_bin_index = /var/lib/mysql/mariadb-bin.index
    relay_log = /var/lib/mysql/relay-bin
    relay_log_index = /var/lib/mysql/relay-bin.index
    pid-file                = /run/mysqld/mysqld.pid
    basedir                 = /usr
    character-set-server  = utf8mb4
    collation-server      = utf8mb4_unicode_ci

  primary.sql: |

    CREATE USER 'maxscale'@'%' IDENTIFIED BY 'maxscale_pw';
    GRANT SELECT ON mysql.user TO 'maxscale'@'%';
    GRANT SELECT ON mysql.db TO 'maxscale'@'%';
    GRANT SELECT ON mysql.tables_priv TO 'maxscale'@'%';
    GRANT SELECT ON mysql.columns_priv TO 'maxscale'@'%';
    GRANT SELECT ON mysql.procs_priv TO 'maxscale'@'%';
    GRANT SELECT ON mysql.proxies_priv TO 'maxscale'@'%';
    GRANT SELECT ON mysql.roles_mapping TO 'maxscale'@'%';
    GRANT SHOW DATABASES ON *.* TO 'maxscale'@'%';
    GRANT REPLICATION CLIENT, REPLICA MONITOR, SUPER, RELOAD, PROCESS, SHOW DATABASES, EVENT on *.* to 'maxscale'@'%';

    CREATE USER 'admin'@'%' IDENTIFIED BY 'admin';
    GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;;

    CREATE USER 'repluser'@'%' IDENTIFIED BY 'replsecret';
    GRANT REPLICATION SLAVE ON *.* TO 'repluser'@'%' WITH GRANT OPTION;
    FLUSH PRIVILEGES;

  slave.sql: |
    # We have to know name of sts (`mariadb-sts`) and 
    # service `mariadb-service` in advance as an FQDN.
    # No need to use master_port

    STOP SLAVE;
    CHANGE MASTER TO 
    MASTER_HOST='mariadb-sts-2.mariadb-service.default.svc.cluster.local',
    MASTER_USER='repluser',
    MASTER_PASSWORD='replsecret',
    MASTER_CONNECT_RETRY=10,
    MASTER_USE_GTID=current_pos;
    START SLAVE;
--- 
apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-maxscale
data:
  maxscale.cnf: |
    [maxscale]
    threads=4

    [Monitor]
    type=monitor
    module=mariadbmon
    servers=server1,server2,server3
    user=admin
    password=admin
    auto_failover=true
    auto_rejoin=true

    [RWSplitRouter]
    type=service
    router=readwritesplit
    servers=server1,server2, server3
    user=maxscale
    password=maxscale_pw

    [RWSplitListener]
    type=listener
    service=RWSplitRouter
    protocol=MariaDBClient
    port=3306

    [server3]
    type=server
    address=mariadb-sts-2.mariadb-service.default.svc.cluster.local
    port=3306
    protocol=MySQLBackend

    [server1]
    type=server
    address=mariadb-sts-0.mariadb-service.default.svc.cluster.local
    port=3306
    protocol=MySQLBackend

    [server2]
    type=server
    address=mariadb-sts-1.mariadb-service.default.svc.cluster.local
    port=3306
    protocol=MySQLBackend
